"""Corrigindo a coluna directors na tabela title_crew

Revision ID: 17c724293d42
Revises: 4c92e1bfd3ff
Create Date: 2025-03-05 21:23:42.409121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17c724293d42'
down_revision: Union[str, None] = '4c92e1bfd3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('title_crew', 'directors',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('title_crew', 'directors',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
