"""update title-crew

Revision ID: 4c92e1bfd3ff
Revises: db4dc706d5a1
Create Date: 2025-03-05 19:48:22.589256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c92e1bfd3ff'
down_revision: Union[str, None] = 'db4dc706d5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('title_crew', 'writers',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('title_crew', 'writers',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
