"""create tables

Revision ID: db4dc706d5a1
Revises: 
Create Date: 2025-03-03 14:32:36.548708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db4dc706d5a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_basics',
    sa.Column('nconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primaryName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birthYear', sa.Integer(), nullable=True),
    sa.Column('deathYear', sa.Integer(), nullable=True),
    sa.Column('primaryProfession', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('knownForTitles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('nconst')
    )
    op.create_table('title_basics',
    sa.Column('tconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titleType', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primaryTitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('originalTitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isAdult', sa.Boolean(), nullable=False),
    sa.Column('startYear', sa.Integer(), nullable=True),
    sa.Column('endYear', sa.Integer(), nullable=True),
    sa.Column('runtimeMinutes', sa.Integer(), nullable=True),
    sa.Column('genres', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table('title_crew',
    sa.Column('tconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('directors', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('writers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tconst'], ['title_basics.tconst'], ),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table('title_principals',
    sa.Column('tconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('nconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('characters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['nconst'], ['name_basics.nconst'], ),
    sa.ForeignKeyConstraint(['tconst'], ['title_basics.tconst'], ),
    sa.PrimaryKeyConstraint('tconst', 'ordering', 'nconst')
    )
    op.create_table('title_ratings',
    sa.Column('tconst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('averageRating', sa.Float(), nullable=False),
    sa.Column('numVotes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tconst'], ['title_basics.tconst'], ),
    sa.PrimaryKeyConstraint('tconst')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_ratings')
    op.drop_table('title_principals')
    op.drop_table('title_crew')
    op.drop_table('title_basics')
    op.drop_table('name_basics')
    # ### end Alembic commands ###
